version: '3'

services:
  front:
    container_name: grunbler-front
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./frontend:/work

  api:
    container_name: grumbler-api
    build: ./backend
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    volumes:
      - ./backend:/go/src/app

  db:
    container_name: grumbler-db
    image: mysql:8.0
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
