FROM golang:1.17 AS builder

WORKDIR /go/src/app
# copy source
COPY . .
RUN go build -o /go/bin/app ./cmd/app/main.go


FROM gcr.io/distroless/base-debian11 AS production

WORKDIR /work
COPY --from=builder /go/bin/app .
COPY --from=builder /go/src/app/env ./env
EXPOSE 8080
ENV GIN_MODE release
CMD ["./app"]
